# Site settings
title: Gustavo Cunha
twitter_username: gmmcal
name: Gustavo Cunha

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
  - title: Site
    url: https://www.gmmcal.com.br
  - title: GitHub
    url: https://github.com/gmmcal
  - title: StackOverflow
    url: https://stackoverflow.com/users/2023462/gustavo-cunha
  - title: LinkedIn
    url: https://www.linkedin.com/in/gmmcal

#Any buzzword skills you want to include
skills:
 - Ruby

#Work experience is required
roles:
  - employer: "KPN"
    title: "Software Engineer"
    description: ""
    start: 2018
    end: Currently
  - employer: "Streetbees"
    title: "Full Stack Developer"
    description: "Full Stack Developer using Ruby, Sinatra, Ruby on Rails, Postgres, Redis, Sidekiq, React, Redux, among others. I work using tools to integrate the workflow routine, such as Trello, Slack and Git."
    start: 2017
    end: 2018
  - employer: "Landing.jobs"
    title: "Senior Software Engineer"
    description: "Senior Software Engineer helping to develop the company platform using Ruby on Rails, Postgres, Redis, Sidekiq. I work using tools to integrate the workflow routine, such as Trello, Skype, Slack and Git, among others."
    start: 2015
    end: 2017
  - employer: "Quimbik, Inc"
    title: "Software Engineer"
    description: "Software Engineer responsible for developing some of the company systems, in a Home Office base, using Ruby on Rails, MySQL, Objective-C and Swift (iOS). I work using tools to integrate the workflow routine, such as Redmine, Pivotal, Skype, Slack and Git, among others."
    start: 2012
    end: 2015
  - employer: "Alagoas Dev Day"
    title: "Cofounder / Organizer"
    description: "Anual development event created to promote and strengthen the programming culture in Alagoas, bringing well known professionals from Brazil to share their experiences."
    start: 2014
    end: Currently
  - employer: "id5 Soluções Web"
    title: "Programmer / System Analyst"
    description: "Responsible for the analysis and development of some of the company systems. I started with maintaining and developing in a decision support system written in ASP / Access. Then, I moved up to take care of the content management systems writen in ASP / SQL Server. In 2010, the company changed the systems to a Wordpress based environment."
    start: 2007
    end: 2012
  - employer: "Correios"
    title: "Development Intern"
    description: "Responsible for maintaing the Regional Intranet of the company and develop new systems, under the close supervision of the System Analysts of the Company."
    start: 2006
    end: 2007
  - employer: "Secretaria de Fazenda de Alagoas / SEFAZ"
    title: "Technical Support Intern"
    description: "Technical Support Intern helping employees to use the computer and its resources. I also helped with data input to a productivity system. By the end of the internship, I developed a PHP system for an internal research."
    start: 2003
    end: 2004

#Education is required
education:
  - level: Bachelor of Science (B.Sc.)
    date: 2008
    subject: Computer Science
    school: Universidade Federal de Alagoas

#This section is optional (as is the image link below)
# coursera:
#    profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
#    courses:
#     - title: Functional Programming Principles in Scala
#       link: https://www.coursera.org/course/progfun
#       optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
#       date: September 16, 2013
#     - title: Algorithms Design and Analysis, Part 1
#       link: https://www.coursera.org/course/progfun
#       optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
#       date: April 28, 2014

#List of interesting Github repo/projects to include - optional
github:
  - gmmcal/gmmcal.com.br
  - alagoasdevday/certificates

#Stackoverflow flair is optional
# stackoverflow:
#   profileurl: http://stackoverflow.com/users/258813/rhinds
#   flairimageurl: http://stackoverflow.com/users/flair/258813.png

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
# additionalinfo: |
#    <strong>JVM</strong>: I am experienced in a variety of Java API’s and frameworks. I have recently worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others.  In my current role Groovy is the primary language used - and I am familiar with many of the languages features and quirks (including writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>). <br/><br/>
#    <strong>Web Development</strong>: My server side web development experience has largely been based on the Spring MVC framework (although current role uses ColdFusion for server side web stack). I have also worked with some client side technology, having used jQuery, Bootstrap, LESS, SASS and have also experimented with other interesting technologies such as Backbone/Underscore/Require.<br/><br/>
#    <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar and Jenkins. I have experience with an array of testing tools and technologies.<br/><br/>
#    I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/Parse. <br/><br/>
#    As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="http://projects.spring.io/spring-social/">http://projects.spring.io/spring-social/</a>. <br/><br/>
#    I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="http://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)
